---
- name: Report PHP module config change
  ansible.builtin.debug:
    msg: "PHP module INI changed; {{ php_fpm_service_name }} will be restarted."

- name: Restart php-fpm
  ansible.builtin.service:
    name: "{{ php_fpm_service_name }}"
    state: restarted

- name: Reload php-fpm
  ansible.builtin.service:
    name: "{{ php_fpm_service_name }}"
    state: reloaded
